name: publish-to-pypi

on:

  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.14'

      - name: Install (build, twine)
        run: |
          pip install build twine

      - name: Build Package
        run: |
          python -m build

      - name: Publish Package To PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/*